CREATE DATABASE zoot;
CREATE USER zoot WITH PASSWORD '1234';
GRANT ALL PRIVILEGES ON DATABASE zoot TO zoot;

\c zoot
GRANT USAGE, CREATE ON SCHEMA public TO zoot;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO zoot;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO zoot;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO zoot;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO zoot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO zoot;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO zoot;
